server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/youquiz
    username: postgres
    password: azer1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /api
